Repository yalesites-org/component-library-twig, pull requests merged in 2022-10, with the labels that each got.

#146 YALB-707: Image grid
  components/03-organisms/_grid-mixins.scss
  components/03-organisms/_list-mixins.scss
  components/03-organisms/card-collection/_yds-card-collection.scss
  components/03-organisms/custom-card-collection/_yds-custom-card-collection.scss
  components/03-organisms/galleries/gallery.stories.js
  components/03-organisms/galleries/media-grid/_yds-media-grid-item.twig
  components/03-organisms/galleries/media-grid/_yds-media-grid-modal.scss
  components/03-organisms/galleries/media-grid/_yds-media-grid.scss
  components/03-organisms/galleries/media-grid/media-grid.yml
  components/03-organisms/galleries/media-grid/yds-media-grid-interactive.js
  components/03-organisms/galleries/media-grid/yds-media-grid.twig
  components/03-organisms/organisms.scss
  images/icons/angle-down.svg
  images/icons/arrows-maximize.svg
  images/icons/circle-info.svg
  images/icons/magnifying-glass.svg
  images/icons/triangle-exclamation.svg
  images/icons/xmark.svg
  system.emulsify.json
Labels: needs review, pass a11y review, pass design review

#152 Release
  components/03-organisms/_grid-mixins.scss
  components/03-organisms/_list-mixins.scss
  components/03-organisms/card-collection/_yds-card-collection.scss
  components/03-organisms/custom-card-collection/_yds-custom-card-collection.scss
  components/03-organisms/galleries/gallery.stories.js
  components/03-organisms/galleries/media-grid/_yds-media-grid-item.twig
  components/03-organisms/galleries/media-grid/_yds-media-grid-modal.scss
  components/03-organisms/galleries/media-grid/_yds-media-grid.scss
  components/03-organisms/galleries/media-grid/media-grid.yml
  components/03-organisms/galleries/media-grid/yds-media-grid-interactive.js
  components/03-organisms/galleries/media-grid/yds-media-grid.twig
  components/03-organisms/organisms.scss
  images/icons/angle-down.svg
  images/icons/arrows-maximize.svg
  images/icons/circle-info.svg
  images/icons/magnifying-glass.svg
  images/icons/triangle-exclamation.svg
  images/icons/xmark.svg
  system.emulsify.json
Labels: don't merge

#153 YALB-722: Interactive grid
  components/00-tokens/effects/_effects.scss
  components/00-tokens/layout/_layout.scss
  components/03-organisms/galleries/gallery.stories.js
  components/03-organisms/galleries/media-grid/_yds-media-grid-item.twig
  components/03-organisms/galleries/media-grid/_yds-media-grid-modal-item--content.twig
  components/03-organisms/galleries/media-grid/_yds-media-grid-modal-item.twig
  components/03-organisms/galleries/media-grid/_yds-media-grid-modal.scss
  components/03-organisms/galleries/media-grid/_yds-media-grid.scss
  components/03-organisms/galleries/media-grid/media-grid.yml
  components/03-organisms/galleries/media-grid/yds-media-grid-interactive.js
  components/03-organisms/galleries/media-grid/yds-media-grid.twig
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.js
  system.emulsify.json
Labels: needs review, pass design review

#154 YALB-756: Rename pop out image to wrapped image
  components/00-tokens/layout/yds-layout.js
  components/02-molecules/molecules.scss
  components/02-molecules/pop-out-image/yds-pop-out-image.twig
  components/02-molecules/wrapped-image/_yds-wrapped-image.scss
  components/02-molecules/wrapped-image/wrapped-image.stories.js
  components/02-molecules/wrapped-image/wrapped-image.yml
  components/02-molecules/wrapped-image/yds-wrapped-image.twig
  components/05-page-examples/_intro-content-examples.twig
  components/05-page-examples/news/news-article.twig
  components/05-page-examples/news/news.stories.js
  components/05-page-examples/standard-pages/standard-page.stories.js
  system.emulsify.json
Labels: needs review, pass design review
