Repository yalesites-org/component-library-twig, pull requests merged in 2022-11, with the labels that each got.

#159 YALB-562 and YALB-563: Header and Footer spacing
  components/00-tokens/colors/_color-pairings.scss
  components/00-tokens/functions/_map.scss
  components/00-tokens/layout/_layout.scss
  components/02-molecules/banner/action/_yds-action-banner.scss
  components/03-organisms/site-header/_yds-site-header.scss
  components/04-page-layouts/page-layouts.scss
Labels: pass code review, pass functional review, pass design review

#156 YALB-784: Remove aria attribute
  components/02-molecules/tabs/yds-tabs.twig
Labels: pass code review, pass functional review

#157 fix: alert dismissal wasn't preserved on page refresh if all alerts on a page had not been interacted with
  components/02-molecules/alert/yds-alert.js
Labels: pass code review, pass functional review, ready to merge

#166 YALB-510: Alerts: Fade away animation
  components/02-molecules/alert/_yds-alert.scss
Labels: pass code review, pass functional review, ready to merge, pass design review

#164 Release
  components/00-tokens/colors/_color-pairings.scss
  components/00-tokens/functions/_map.scss
  components/00-tokens/layout/_layout.scss
  components/02-molecules/alert/_yds-alert.scss
  components/02-molecules/alert/yds-alert.js
  components/02-molecules/banner/action/_yds-action-banner.scss
  components/02-molecules/callout/_yds-callout.scss
  components/02-molecules/callout/_yds-callout.twig
  components/02-molecules/callout/callout.yml
  components/02-molecules/tabs/yds-tabs.twig
  components/03-organisms/site-header/_yds-site-header.scss
  components/04-page-layouts/page-layouts.scss
Labels: don't merge

#167 YALB-823: Type changes from printer
  components/00-tokens/typography/_typography.scss
  components/01-atoms/date-time/_yds-date-time.scss
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/menu/_yds-menu.scss
  components/02-molecules/meta/event-meta/_yds-event-meta.scss
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  package-lock.json
Labels: needs review, pass design review

#161 YALB-696: Header navigation alignment
  components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
Labels: pass code review, pass functional review, ready to merge, pass design review

#165 YALB-797 CTA Banner White BG Variation - bottom border
  components/02-molecules/banner/action/_yds-action-banner.scss
Labels: pass code review, pass functional review, pass design review

#170 YALB-765: max width for elements
  package-lock.json
Labels: needs review, pass code review, pass design review

#172 YALB-789 - image wrapped variations
  components/00-tokens/layout/_layout.scss
  components/01-atoms/typography/text/_yds-text.scss
  components/02-molecules/wrapped-image/_yds-wrapped-image.scss
  components/02-molecules/wrapped-image/wrapped-image.stories.js
  components/02-molecules/wrapped-image/yds-wrapped-image.twig
  package-lock.json
Labels: pass code review, pass functional review, ready to merge, pass design review
