Repository yalesites-org/component-library-twig, pull requests merged in 2022-08, with the labels that each got.

#113 YALB-350: Component tokens
  components/00-tokens/typography/_typography.scss
  components/00-tokens/utility/_utility.scss
  components/01-atoms/controls/cta/_cta.scss
  components/01-atoms/controls/text-link/_text-link.scss
  components/02-molecules/accordion/_accordion.scss
  components/02-molecules/alert/_alert.scss
  components/02-molecules/menu/_menu.scss
  components/02-molecules/pager/_pager.scss
  components/02-molecules/social-links/_social-links.scss
  components/02-molecules/tabs/_tabs.scss
  components/03-organisms/menu/utility-nav/_utility-nav.scss
  components/_settings/_config.css
  package-lock.json
Labels: pass code review, pass functional review, Question

#112 YALB-474: Controls refactor
  components/01-atoms/controls/base/control.twig
  components/01-atoms/controls/cta/cta.twig
  components/02-molecules/accordion/_accordion-item.twig
  components/02-molecules/accordion/accordion.twig
  components/02-molecules/alert/alert.twig
  components/02-molecules/menu/_menu-item.twig
  components/02-molecules/menu/menu-toggle/menu-toggle.twig
  components/02-molecules/social-links/_social-link__content.twig
  components/02-molecules/social-links/_social-links.scss
  components/02-molecules/social-links/social-links.twig
  components/03-organisms/menu/breadcrumbs/breadcrumbs.twig
Labels: needs review, pass code review

#116 YALB-106: refactor tabs to support drupal
  components/02-molecules/tabs/_tab-content.twig
  components/02-molecules/tabs/_tab-label.twig
  components/02-molecules/tabs/tabs.twig
Labels: needs review

#121 YALB-627: hiding breadcrumbs short trails
  components/03-organisms/menu/breadcrumbs/breadcrumbs.twig
Labels: pass code review

#119 YALB-635: Wire Breadcrumbs
  components/02-molecules/menu/_menu-item.twig
  components/02-molecules/menu/menu.twig
Labels: pass code review, pass functional review

#127 YALB-101: Custom card molecule
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
  components/02-molecules/cards/custom-card/custom-card.stories.js
  components/02-molecules/cards/custom-card/custom-card.yml
  components/02-molecules/cards/custom-card/yds-custom-card.js
  components/02-molecules/cards/custom-card/yds-custom-card.twig
  components/02-molecules/molecules.scss
  components/03-organisms/custom-card-collection/_yds-custom-card-collection.scss
  components/03-organisms/custom-card-collection/custom-card-collection.stories.js
  components/03-organisms/custom-card-collection/yds-custom-card-collection.twig
  components/03-organisms/organisms.scss
  system.emulsify.json
Labels: needs review, pass code review, pass functional review

#128 YALB-647: updates page title spacing
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  components/03-organisms/site-header/_yds-site-header.scss
Labels: pass code review, pass functional review, pass a11y review, pass design review

#132 YALB-649: Feedback: Update spacing on accordions
  components/02-molecules/accordion/_yds-accordion.scss
Labels: needs review, pass code review
