Repository yalesites-org/component-library-twig, pull requests merged in 2022-12, with the labels that each got.

#173 YALB-767 - Basic Nav Organism
  components/02-molecules/menu/_yds-menu-item.twig
  components/02-molecules/menu/yds-menu.twig
  components/03-organisms/_list-mixins.scss
  components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
  components/03-organisms/menu/primary-nav/primary-nav.stories.js
  components/03-organisms/menu/primary-nav/primary-nav.yml
  components/03-organisms/menu/primary-nav/yds-primary-nav.twig
  components/03-organisms/site-header/site-header.stories.js
  components/04-page-layouts/page-layouts.stories.js
  components/05-page-examples/events/events.stories.js
  components/05-page-examples/miscellaneous/miscellaneous-page.stories.js
  components/05-page-examples/news/news.stories.js
  components/05-page-examples/standard-pages/standard-page.stories.js
  components/_settings/config.stories.js
Labels: needs review, pass a11y review, pass design review

#177 YALB-824: Feedback: Small size header border shrink
  components/03-organisms/site-header/_yds-site-header.scss
Labels: needs review, pass code review, pass design review

#176 YALB-96/600: Search Theming
  components/02-molecules/molecules.scss
  components/02-molecules/search-result/_yds-search-result.scss
  components/02-molecules/search-result/breadcrumbs.yml
  components/02-molecules/search-result/search-result.yml
  components/02-molecules/search-result/yds-search-result.stories.js
  components/02-molecules/search-result/yds-search-result.twig
  components/03-organisms/component-wrapper/component-wrapper.stories.js
  components/03-organisms/component-wrapper/yds-component-wrapper.twig
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.js
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig
  components/03-organisms/menu/utility-nav/yds-utility-nav.twig
Labels: needs review, pass code review, pass design review

#174 YALB-833: Grand Hero component
  components/01-atoms/controls/text-link/_yds-text-link.scss
  components/02-molecules/banner/action/yds-action-banner.twig
  components/02-molecules/banner/banner.stories.js
  components/02-molecules/banner/grand-hero.yml
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
  components/02-molecules/molecules.scss
  components/03-organisms/site-header/site-header.stories.js
  components/03-organisms/site-header/yds-site-header.js
  components/04-page-layouts/page-layouts.scss
  components/05-page-examples/standard-pages/standard-page-with-banner.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
Labels: pass code review, pass design review

#171 Release
  .vscode/settings.json
  components/00-tokens/layout/_layout.scss
  components/01-atoms/controls/text-link/_yds-text-link.scss
  components/01-atoms/typography/text/_yds-text.scss
  components/02-molecules/banner/action/yds-action-banner.twig
  components/02-molecules/banner/banner.stories.js
  components/02-molecules/banner/grand-hero.yml
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/menu/_yds-menu-item.twig
  components/02-molecules/menu/yds-menu.twig
  components/02-molecules/molecules.scss
  components/02-molecules/search-result/_yds-search-result.scss
  components/02-molecules/search-result/breadcrumbs.yml
  components/02-molecules/search-result/search-result.yml
  components/02-molecules/search-result/yds-search-result.stories.js
  components/02-molecules/search-result/yds-search-result.twig
  components/02-molecules/wrapped-image/_yds-wrapped-image.scss
  components/02-molecules/wrapped-image/wrapped-image.stories.js
  components/02-molecules/wrapped-image/yds-wrapped-image.twig
  components/03-organisms/_grid-mixins.scss
  components/03-organisms/_list-mixins.scss
  components/03-organisms/component-wrapper/component-wrapper.stories.js
  components/03-organisms/component-wrapper/yds-component-wrapper.twig
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.js
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig
  components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
  components/03-organisms/menu/primary-nav/primary-nav.stories.js
  components/03-organisms/menu/primary-nav/primary-nav.yml
  components/03-organisms/menu/primary-nav/yds-primary-nav.twig
  components/03-organisms/menu/utility-nav/yds-utility-nav.twig
  components/03-organisms/site-header/_yds-site-header.scss
  components/03-organisms/site-header/site-header.stories.js
  components/03-organisms/site-header/yds-site-header.js
  components/04-page-layouts/page-layouts.scss
  components/04-page-layouts/page-layouts.stories.js
  components/05-page-examples/events/events.stories.js
  components/05-page-examples/miscellaneous/miscellaneous-page.stories.js
  components/05-page-examples/news/news.stories.js
  components/05-page-examples/standard-pages/standard-page-with-banner.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
  components/_settings/config.stories.js
  package-lock.json
Labels: released

#179 fix: update to latest tokens release
  package-lock.json
Labels: pass code review, pass design review
