Repository yalesites-org/component-library-twig, pull requests merged in 2022-07, with the labels that each got.

#99 YALB-561: text with image spacing
  components/02-molecules/text-with-image/_text-with-image.scss
Labels: pass code review, ready to merge, pass design review

#104 YALB-620: Fix deployed storybook
  package.json
Labels: needs review, pass code review, pass functional review, ready to merge

#105 Release
  components/00-tokens/effects/_effects.scss
  components/01-atoms/controls/cta/_cta.scss
  components/01-atoms/controls/text-link/_text-link.scss
  components/02-molecules/accordion/_accordion.scss
  components/02-molecules/text-with-image/_text-with-image.scss
  components/03-organisms/site-header/_site-header.scss
  components/_settings/_config.css
  package-lock.json
  package.json
Labels: don't merge

#102 YALB-78: Pagination
  .storybook/setupTwig.js
  components/02-molecules/cards/reference-card/examples/_card--examples.twig
  components/02-molecules/menu/_menu-item.twig
  components/02-molecules/molecules.scss
  components/02-molecules/pager/_pager.scss
  components/02-molecules/pager/cl-pager.js
  components/02-molecules/pager/pager-first-and-last.yml
  components/02-molecules/pager/pager-first.yml
  components/02-molecules/pager/pager-last.yml
  components/02-molecules/pager/pager.stories.js
  components/02-molecules/pager/pager.twig
  components/02-molecules/pager/pager.yml
  components/03-organisms/menu/primary-nav/primary-nav.yml
  components/05-page-examples/events/_event-collection--example.twig
  components/05-page-examples/events/event-grid.twig
  components/05-page-examples/events/event-list.twig
  components/05-page-examples/events/events.stories.js
  system.emulsify.json
Labels: needs work, pass a11y review, pass design review

#107 YALB-621: adds social links component
  components/00-tokens/colors/color-pairings.twig
  components/02-molecules/molecules.scss
  components/02-molecules/social-links/_social-links.scss
  components/02-molecules/social-links/social-links.stories.js
  components/02-molecules/social-links/social-links.twig
  components/02-molecules/social-links/social-links.yml
  images/icons/facebook.svg
  images/icons/flickr.svg
  images/icons/instagram.svg
  images/icons/linkedin.svg
  images/icons/soundcloud.svg
  images/icons/tiktok.svg
  images/icons/twitter.svg
  images/icons/weibo.svg
  images/icons/youtube.svg
Labels: needs review, pass a11y review, pass design review

#106 YALB-611: Tabs component
  components/00-tokens/effects/_effects.scss
  components/01-atoms/controls/base/control.twig
  components/01-atoms/controls/text-link/_text-link.scss
  components/02-molecules/molecules.scss
  components/02-molecules/tabs/_tabs.scss
  components/02-molecules/tabs/tabs.js
  components/02-molecules/tabs/tabs.stories.js
  components/02-molecules/tabs/tabs.twig
  components/02-molecules/tabs/tabs.yml
  package-lock.json
  system.emulsify.json
Labels: needs review, pass a11y review, pass design review
