Repository yalesites-org/component-library-twig, pull requests merged in 2022-09, with the labels that each got.

#131 YALB-668: Feedback: First Tab selection on page load
  components/02-molecules/tabs/_yds-tab-label.twig
Labels: pass code review, pass functional review, ready to merge

#123 YALB-34: create quick links molecule
  components/01-atoms/controls/cta/yds-cta.twig
  components/02-molecules/cards/custom-card/yds-custom-card.twig
  components/02-molecules/molecules.scss
  components/02-molecules/quick-links/_yds-quick-links--links.twig
  components/02-molecules/quick-links/_yds-quick-links.scss
  components/02-molecules/quick-links/quick-links.stories.js
  components/02-molecules/quick-links/quick-links.yml
  components/02-molecules/quick-links/yds-quick-links.twig
  components/05-page-examples/standard-pages/standard-page-with-quicklinks.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
Labels: pass code review, pass a11y review

#126 YALB-650: update date and time for news/event pages
  components/01-atoms/date-time/_yds-date-time.scss
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/meta/basic-meta/_yds-basic-meta.scss
  components/02-molecules/meta/event-meta/yds-event-meta.twig
  components/02-molecules/meta/meta.stories.js
Labels: pass code review

#134 YALB-293: Namespace event format
  components/02-molecules/cards/reference-card/event/_yds-event-format.twig
  components/02-molecules/cards/reference-card/examples/_card--examples.twig
  components/02-molecules/meta/event-meta/yds-event-meta.twig
Labels: pass code review, pass functional review

#133 Release
  components/01-atoms/controls/cta/yds-cta.twig
  components/01-atoms/date-time/_yds-date-time.scss
  components/02-molecules/accordion/_yds-accordion.scss
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
  components/02-molecules/cards/custom-card/custom-card.stories.js
  components/02-molecules/cards/custom-card/custom-card.yml
  components/02-molecules/cards/custom-card/yds-custom-card.js
  components/02-molecules/cards/custom-card/yds-custom-card.twig
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/event/_yds-event-format.twig
  components/02-molecules/cards/reference-card/examples/_card--examples.twig
  components/02-molecules/meta/basic-meta/_yds-basic-meta.scss
  components/02-molecules/meta/event-meta/yds-event-meta.twig
  components/02-molecules/meta/meta.stories.js
  components/02-molecules/molecules.scss
  components/02-molecules/quick-links/_yds-quick-links--links.twig
  components/02-molecules/quick-links/_yds-quick-links.scss
  components/02-molecules/quick-links/quick-links.stories.js
  components/02-molecules/quick-links/quick-links.yml
  components/02-molecules/quick-links/yds-quick-links.twig
  components/02-molecules/tabs/_yds-tab-label.twig
  components/03-organisms/custom-card-collection/_yds-custom-card-collection.scss
  components/03-organisms/custom-card-collection/custom-card-collection.stories.js
  components/03-organisms/custom-card-collection/yds-custom-card-collection.twig
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  components/03-organisms/organisms.scss
  components/03-organisms/site-header/_yds-site-header.scss
  components/05-page-examples/standard-pages/standard-page-with-quicklinks.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
  system.emulsify.json
Labels: don't merge

#137 YALB-94: quick-links wiring
  components/02-molecules/quick-links/_yds-quick-links--links.twig
  components/02-molecules/quick-links/yds-quick-links.twig
  components/03-organisms/custom-card-collection/yds-custom-card-collection.twig
Labels: pass code review, pass functional review

#130 YALB-615: Long Breadcrumbs
  components/02-molecules/menu/_yds-menu-item.twig
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  components/03-organisms/menu/breadcrumbs/breadcrumbs.yml
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.js
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig
Labels: needs review, pass a11y review

#135 YALB-526: Table styles
  components/01-atoms/atoms.scss
  components/01-atoms/tables/_table.scss
  components/01-atoms/tables/example-tables.twig
  components/01-atoms/tables/table.stories.js
  system.emulsify.json
Labels: needs review

#143 YALB-670: hides level 4 children in main menu
  components/02-molecules/menu/_yds-menu-item.twig
Labels: pass code review, pass functional review, ready to merge

#141 YALB-720: changes date font to uppercase capitals
  components/01-atoms/date-time/_yds-date-time.scss
Labels: pass code review, pass functional review, ready to merge, pass design review

#139 YALB-688: Update Component Names in Storybook
  components/02-molecules/banner/action/_yds-action-banner.scss
  components/02-molecules/banner/action/yds-action-banner.twig
  components/02-molecules/banner/banner.stories.js
  components/02-molecules/molecules.scss
  components/05-page-examples/standard-pages/standard-page-with-banner.twig
Labels: pass functional review, pass design review

#144 YALB-598: Global Settings
  .percyrc
  .storybook/preview.js
  README.md
  components/00-tokens/breakpoints/breakpoints.twig
  components/00-tokens/cl-base.scss
  components/00-tokens/spacing/spacing.twig
  components/01-atoms/controls/cta/_yds-cta.scss
  components/01-atoms/divider/_yds-divider.scss
  components/01-atoms/divider/divider.stories.js
  components/01-atoms/divider/yds-divider.twig
  components/01-atoms/tables/_table.scss
  components/01-atoms/tables/example-tables.twig
  components/02-molecules/tabs/_yds-tabs.scss
  components/02-molecules/text/_yds-text-field.scss
  components/03-organisms/layout/two-column/_yds-two-column.scss
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
  components/03-organisms/site-header/yds-site-header.twig
  components/04-page-layouts/cl-page-args.js
  components/05-page-examples/events/event-grid.twig
  components/05-page-examples/events/events.stories.js
  components/05-page-examples/miscellaneous/miscellaneous-page.stories.js
  components/05-page-examples/news/news.stories.js
  components/05-page-examples/standard-pages/standard-page.stories.js
  components/_settings/_config.css
  components/_settings/config.js
  components/_settings/config.stories.js
  components/_settings/config.twig
  package-lock.json
Labels: pass code review, pass a11y review, pass design review

#145 YALB-711: creates video component
  components/01-atoms/atoms.scss
  components/01-atoms/video-embed/_yds-video-embed.scss
  components/01-atoms/video-embed/video-embed.stories.js
  components/01-atoms/video-embed/video-embed.yml
  components/01-atoms/video-embed/yds-video-embed.twig
  components/02-molecules/molecules.scss
  components/02-molecules/video/_yds-video.scss
  components/02-molecules/video/video.stories.js
  components/02-molecules/video/video.yml
  components/02-molecules/video/yds-video.twig
  components/05-page-examples/standard-pages/standard-page-with-video.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
  system.emulsify.json
Labels: pass code review, pass functional review, ready to merge, pass a11y review, pass design review

#148 Release
  components/01-atoms/atoms.scss
  components/01-atoms/video-embed/_yds-video-embed.scss
  components/01-atoms/video-embed/video-embed.stories.js
  components/01-atoms/video-embed/video-embed.yml
  components/01-atoms/video-embed/yds-video-embed.twig
  components/02-molecules/molecules.scss
  components/02-molecules/video/_yds-video.scss
  components/02-molecules/video/video.stories.js
  components/02-molecules/video/video.yml
  components/02-molecules/video/yds-video.twig
  components/05-page-examples/standard-pages/standard-page-with-video.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
  system.emulsify.json
Labels: don't merge

#147 YALB-700: Search Form
  components/03-organisms/menu/utility-nav/_utility-nav--menu.twig
  components/03-organisms/menu/utility-nav/yds-utility-nav.twig
Labels: pass code review, pass functional review

#149 YALB-702: Search: Hide search form
  components/03-organisms/menu/utility-nav/yds-utility-nav.twig
Labels: needs review, pass functional review
