Repository yalesites-org/component-library-twig, pull requests merged in 2023-04, with the labels that each got.

#214 YALB-1052: Feedback: H1 spacing
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  components/04-page-layouts/page-layouts.scss
  components/05-page-examples/events/event-page.twig
  components/05-page-examples/events/events.stories.js
Labels: pass code review, pass functional review, pass design review

#216 YALB-1093: Fix accordion animation
  components/02-molecules/accordion/_yds-accordion.scss
Labels: pass code review, pass functional review, ready to merge

#213 fix(yalb-alignment): update ql sublte width, wrapped image defaults, …
  .storybook/preview.js
  components/00-tokens/layout/_layout.scss
  components/00-tokens/layout/cl-layout.scss
  components/01-atoms/divider/yds-divider.twig
  components/01-atoms/forms/textfields/_yds-textfields.scss
  components/02-molecules/banner/action/_yds-action-banner.scss
  components/02-molecules/banner/action/yds-action-banner.twig
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
  components/02-molecules/callout/_yds-callout.scss
  components/02-molecules/page-title/_yds-page-title.scss
  components/02-molecules/pull-quote/_yds-pull-quote.scss
  components/02-molecules/quick-links/_yds-quick-links.scss
  components/02-molecules/quick-links/yds-quick-links.twig
  components/02-molecules/tabs/_yds-tabs.scss
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/02-molecules/text-with-image/text-with-image.stories.js
  components/02-molecules/text/_yds-text-field.scss
  components/02-molecules/wrapped-image/_yds-wrapped-image.scss
  components/02-molecules/wrapped-image/wrapped-image.stories.js
  components/02-molecules/wrapped-image/yds-wrapped-image.twig
  components/03-organisms/_grid-mixins.scss
  components/03-organisms/galleries/media-grid/_yds-media-grid.scss
  components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
  components/03-organisms/site-footer/_yds-site-footer.scss
  components/05-page-examples/_intro-content-examples.twig
  components/05-page-examples/events/event-grid.twig
  components/05-page-examples/events/event-list.twig
  components/05-page-examples/events/event-page.twig
  components/05-page-examples/miscellaneous/accordion-page.twig
  components/05-page-examples/news/news-article.twig
  components/05-page-examples/standard-pages/standard-page-short.twig
  components/05-page-examples/standard-pages/standard-page-with-banner-left-align.twig
  components/05-page-examples/standard-pages/standard-page-with-banner.twig
  components/05-page-examples/standard-pages/standard-page-with-quicklinks.twig
  components/05-page-examples/standard-pages/standard-page-with-video.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
  components/05-page-examples/standard-pages/standard-page.twig
  package-lock.json
Labels: pass code review, ready to merge, pass design review

#217 YALB-1095: Add darker background for media gallery
  components/03-organisms/galleries/media-grid/yds-media-grid.twig
Labels: pass code review, pass functional review, ready to merge, pass design review

#215 YALB-1051: Accordion spacing
  components/02-molecules/text/yds-text-field.twig
Labels: pass code review, pass functional review, ready to merge

#223 fix(yalb-1094): hidden alert no longer flickers on page load
  components/02-molecules/alert/_yds-alert.scss
  components/02-molecules/alert/yds-alert.js
Labels: pass code review, pass functional review, ready to merge

#222 fix(yalb-1104): alignment fixes part 2
  components/01-atoms/divider/yds-divider.twig
  components/01-atoms/images/image/cl-image.scss
  components/01-atoms/typography/headings/_yds-headings.scss
  components/02-molecules/accordion/yds-accordion.twig
  components/02-molecules/banner/action/yds-action-banner.twig
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
  components/02-molecules/callout/yds-callout.twig
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
  components/02-molecules/embed/yds-embed.twig
  components/02-molecules/image/yds-content-image.twig
  components/02-molecules/pull-quote/yds-pull-quote.twig
  components/02-molecules/quick-links/_yds-quick-links.scss
  components/02-molecules/quick-links/yds-quick-links.twig
  components/02-molecules/tabs/yds-tabs.twig
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/02-molecules/text-with-image/yds-text-with-image.twig
  components/02-molecules/text/yds-text-field.twig
  components/02-molecules/video/yds-video.twig
  components/02-molecules/wrapped-image/yds-wrapped-image.twig
  components/03-organisms/component-wrapper/yds-component-wrapper.twig
  components/03-organisms/custom-card-collection/yds-custom-card-collection.twig
  components/03-organisms/galleries/media-grid/_yds-media-grid.scss
  components/03-organisms/galleries/media-grid/yds-media-grid.twig
  components/03-organisms/menu/utility-nav/_yds-utility-nav.scss
  components/03-organisms/site-header/site-header.stories.js
  components/04-page-layouts/page-layouts.scss
  components/05-page-examples/standard-pages/standard-page.twig
Labels: pass code review, pass design review

#227 YALB-984 - Part Three - Refine Global Theme tokens and label names in storybook
  components/00-tokens/colors/_color-global-themes.scss
  components/00-tokens/colors/color-component-theme-pairings.twig
  components/00-tokens/colors/color-global-theme-pairings.twig
  components/00-tokens/colors/color-global-themes.js
  components/00-tokens/colors/color-global-themes.twig
  components/00-tokens/colors/colors.stories.js
  components/01-atoms/controls/control.stories.js
  components/01-atoms/controls/cta/_yds-cta.scss
  components/01-atoms/controls/text-link/_yds-text-link.scss
  components/01-atoms/controls/text-link/yds-text-link.js
  components/02-molecules/banner/action/_yds-action-banner.scss
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/callout/_yds-callout.scss
  components/02-molecules/callout/callout.stories.js
  components/02-molecules/pull-quote/_yds-pull-quote.scss
  components/02-molecules/quick-links/_yds-quick-links.scss
  components/02-molecules/tabs/_yds-tabs.scss
  components/03-organisms/site-footer/_yds-site-footer.scss
  components/03-organisms/site-footer/site-footer.stories.js
  components/03-organisms/site-header/_yds-site-header.scss
  components/03-organisms/site-header/site-header.stories.js
  components/_settings/config.stories.js
  components/_settings/config.twig
  package-lock.json
Labels: pass code review, pass functional review, ready to merge

#231 YALB-1162 - Cards: Custom cards style updates
  components/00-tokens/colors/cl-colors.scss
  components/00-tokens/colors/color-global-theme-pairings.twig
  components/01-atoms/controls/text-link/_yds-text-link.scss
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
  components/03-organisms/custom-card-collection/custom-card-collection.stories.js
  package-lock.json
Labels: pass code review, ready to merge, pass design review
