Repository yalesites-org/component-library-twig, pull requests merged in 2023-02, with the labels that each got.

#197 YALB-399: Feedback: Update to Pull Quote
  components/02-molecules/pull-quote/_yds-pull-quote.scss
Labels: needs review, pass a11y review

#198 YALB-980: Adjust component-width
  components/02-molecules/page-title/yds-page-title.twig
  components/02-molecules/text/yds-text-field.twig
  components/03-organisms/custom-card-collection/yds-custom-card-collection.twig
  components/03-organisms/galleries/media-grid/yds-media-grid.twig
  components/03-organisms/site-footer/yds-site-footer.twig
  package-lock.json
Labels: pass code review, pass functional review, ready to merge

#204 YALB-974 - Breadcrumb: Home link broken
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
Labels: needs review

#206 YALB-820: Move local tasks
  components/02-molecules/tabs/yds-tabs.twig
Labels: pass code review, pass functional review, ready to merge

#195 fix: new link__type to denote external and new-target link types
  .storybook/preview.js
  components/01-atoms/atoms.scss
  components/01-atoms/controls/control.stories.js
  components/01-atoms/controls/text-link/_yds-text-link.scss
  components/01-atoms/controls/text-link/yds-text-link.js
  components/01-atoms/controls/text-link/yds-text-link.twig
  components/01-atoms/images/fa-icons/_yds-fa-icon.twig
  components/01-atoms/images/fa-icons/_yds-fa-icons.scss
  components/01-atoms/images/fa-icons/fa-icons.yml
  components/01-atoms/images/fa-icons/yds-fa-icons.twig
  components/01-atoms/images/images.stories.js
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
  components/03-organisms/galleries/media-grid/_yds-media-grid-modal.scss
  components/05-page-examples/news/news-grid.twig
  components/05-page-examples/news/news.stories.js
  fonts/fontawesome/css/fontawesome.css
  fonts/fontawesome/css/fontawesome.min.css
  fonts/fontawesome/css/regular.css
  fonts/fontawesome/css/regular.min.css
  fonts/fontawesome/css/solid.css
  fonts/fontawesome/css/solid.min.css
  fonts/fontawesome/webfonts/fa-regular-400.ttf
  fonts/fontawesome/webfonts/fa-regular-400.woff2
  fonts/fontawesome/webfonts/fa-solid-900.ttf
  fonts/fontawesome/webfonts/fa-solid-900.woff2
  images/icons/circle-down.svg
  images/icons/link-external-custom.svg
  images/icons/link-external.svg
  images/icons/link-target-blank.svg
Labels: needs review, pass a11y review

#208 YALB-858: Updating the mixing for branding-small
  components/03-organisms/site-header/_yds-site-header.scss
Labels: pass code review, pass functional review, ready to merge
