Repository yalesites-org/component-library-twig, pull requests merged in 2023-09, with the labels that each got.

#284 YALB 1511 - Theming Primary Navigation Headings
  components/01-atoms/lists/_yds-list-item.twig
  components/01-atoms/lists/list.yml
  components/01-atoms/lists/yds-list.twig
  components/02-molecules/menu/_yds-menu-item.twig
  components/02-molecules/menu/_yds-menu-list.twig
  components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
  components/03-organisms/menu/primary-nav/primary-nav.yml
Labels: needs review, pass code review, pass design review

#285 YALB-1215: Dials: Banner heading levels
  components/02-molecules/banner/action/yds-action-banner.twig
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
Labels: pass code review, pass functional review

#283 YALB 1487 - Fat Footer Branding: FE
  components/02-molecules/link-group/_yds-link-group--links.twig
  components/02-molecules/link-group/_yds-link-group.scss
  components/02-molecules/link-group/link-group.stories.js
  components/02-molecules/link-group/link-group.yml
  components/02-molecules/link-group/yds-link-group.twig
  components/02-molecules/molecules.scss
  components/03-organisms/site-footer/_site-footer--examples.twig
  components/03-organisms/site-footer/_site-footer-basic.twig
  components/03-organisms/site-footer/_site-footer-mega.twig
  components/03-organisms/site-footer/_yds-site-footer.scss
  components/03-organisms/site-footer/site-footer.stories.js
  components/03-organisms/site-footer/yds-site-footer.twig
  components/05-page-examples/events/events.stories.js
  components/05-page-examples/miscellaneous/miscellaneous-page.stories.js
  components/05-page-examples/post/post.stories.js
  components/05-page-examples/profiles/profiles.stories.js
  components/05-page-examples/standard-pages/standard-page.stories.js
  components/_settings/config.stories.js
Labels: pass code review, pass functional review, ready to merge

#286 YALB-1505 - Controls: Disable animation per block
  components/00-tokens/effects/yds-animate.js
  components/01-atoms/divider/_yds-divider.scss
  components/01-atoms/divider/yds-divider.twig
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/pull-quote/_yds-pull-quote.scss
  components/02-molecules/pull-quote/yds-pull-quote.twig
  components/03-organisms/card-collection/yds-card-collection.twig
  components/05-page-examples/_intro-content-examples.twig
  components/05-page-examples/events/_event-collection--example.twig
  components/05-page-examples/events/event-page.twig
  components/05-page-examples/post/post-article.twig
  components/05-page-examples/post/post-grid.twig
  components/05-page-examples/post/post.stories.js
  components/05-page-examples/profiles/profile.twig
  components/05-page-examples/standard-pages/standard-page-with-banner-left-align.twig
  components/05-page-examples/standard-pages/standard-page-with-banner.twig
  components/05-page-examples/standard-pages/standard-page.twig
Labels: pass code review, pass functional review

#287 YALB-1311 - Bug: Button Link alignment incorrect | YALB-1457 - Bug: Linked email needs link style/treatment | YALB-1480 - Bug: FE: spacing under the button block | YALB-1506 - Bug: Cursor pointer for email copy link
  components/01-atoms/controls/cta/_yds-cta.scss
  components/01-atoms/controls/text-link/_yds-text-link.scss
  components/01-atoms/controls/text-link/yds-text-link.twig
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/02-molecules/text/_yds-text-field.scss
  components/02-molecules/wrapped-image/_yds-wrapped-image.scss
  components/03-organisms/component-wrapper/_yds-component-wrapper.scss
Labels: pass code review, pass functional review, ready to merge

#290 fix(yalb-mega-footer-2): remove two footer logos from mega footer, ch…
  components/02-molecules/link-group/_yds-link-group.scss
  components/02-molecules/social-links/_yds-social-links.scss
  components/03-organisms/site-footer/_site-footer-mega.twig
  components/03-organisms/site-footer/_yds-site-footer.scss
Labels: needs review

#292 YALB-1423 - Feedback: Rename floated to inline | YALB-1425 - Bug: Firefox - GIF being uploaded to multiple blocks | YALB-1426 - Bug: Exposed taxonomy filter style on mobile
  components/01-atoms/forms/_yds-form.scss
  components/03-organisms/galleries/media-grid/yds-media-grid-interactive.js
Labels: pass code review, pass functional review

#300 YALB-1410: Bug: Accessibility (FE)- Color Contrast issues in automatic testing tools
  components/02-molecules/banner/action/_yds-action-banner.scss
  components/02-molecules/banner/action/yds-action-banner.twig
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
Labels: needs review, pass code review, pass functional review, pass a11y review
