Repository yalesites-org/component-library-twig, pull requests merged in 2023-01, with the labels that each got.

#181 YALB-840 - Grand Hero: Video background
  components/01-atoms/atoms.scss
  components/01-atoms/videos/video-background/video-background.stories.js
  components/01-atoms/videos/video-background/video-background.yml
  components/01-atoms/videos/video-background/yds-video-background.js
  components/01-atoms/videos/video-background/yds-video-background.scss
  components/01-atoms/videos/video-background/yds-video-background.twig
  components/01-atoms/videos/video-embed/_yds-video-embed.scss
  components/01-atoms/videos/video-embed/video-embed.stories.js
  components/01-atoms/videos/video-embed/video-embed.yml
  components/01-atoms/videos/video-embed/yds-video-embed.twig
  components/02-molecules/banner/banner.stories.js
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
  components/02-molecules/video/yds-video.twig
  images/icons/circle-pause.svg
  images/icons/circle-play.svg
  images/icons/pause.svg
  images/icons/play.svg
Labels: pass code review, pass functional review, pass design review

#183 yalb-794 - Feedback: Breadcrumb spacing
  components/04-page-layouts/page-layouts.scss
Labels: pass code review, pass design review

#180 YALB-851 - Forms: Text inputs in Storybook | YALB-893 - Forms: Example form in storybook
  components/01-atoms/atoms.scss
  components/01-atoms/forms/_form-label.twig
  components/01-atoms/forms/_input.twig
  components/01-atoms/forms/_textarea.twig
  components/01-atoms/forms/_yds-form.scss
  components/01-atoms/forms/checkbox/_yds-checkbox-item.twig
  components/01-atoms/forms/checkbox/_yds-checkbox.scss
  components/01-atoms/forms/checkbox/checkbox.yml
  components/01-atoms/forms/checkbox/yds-checkbox.twig
  components/01-atoms/forms/contact-form-example.twig
  components/01-atoms/forms/forms.stories.js
  components/01-atoms/forms/radio/_yds-radio-item.twig
  components/01-atoms/forms/radio/_yds-radio.scss
  components/01-atoms/forms/radio/radio.yml
  components/01-atoms/forms/radio/yds-radio.twig
  components/01-atoms/forms/select/_yds-select-item.twig
  components/01-atoms/forms/select/_yds-select.scss
  components/01-atoms/forms/select/select.yml
  components/01-atoms/forms/select/yds-select.twig
  components/01-atoms/forms/textfields/_yds-textfields.scss
  components/01-atoms/forms/textfields/yds-textfields.twig
  images/icons/circle-exclamation.svg
Labels: needs review, pass a11y review, pass design review

#184 YALB-462 - Embeds: Theming Elements
  components/02-molecules/embed/_yds-embed.scss
  components/02-molecules/embed/yds-embed.twig
Labels: pass code review, pass functional review, ready to merge

#189 YALB-871 - Feedback: Printer's type changes
  components/01-atoms/controls/text-link/_yds-text-link.scss
  package-lock.json
Labels: needs review

#185 YALB-913: Bug: Search results page
  components/01-atoms/controls/cta/_yds-cta.scss
  components/01-atoms/forms/textfields/_yds-textfields.scss
  components/02-molecules/search-result/_yds-search-result.scss
Labels: pass code review, pass functional review, ready to merge

#187 YALB-908 - Bug: Text link style bug for Callout
  components/02-molecules/callout/_yds-callout.scss
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
Labels: pass code review, pass functional review, ready to merge

#190 YALB-888: Feedback: Update Footer links
  components/03-organisms/site-footer/_yds-site-footer.scss
  components/03-organisms/site-footer/yds-site-footer.twig
Labels: pass code review, pass functional review, ready to merge

#196 YALB-844: Capture "bottom-only" shadow as token
  components/00-tokens/effects/cl-effects.scss
  components/00-tokens/effects/effects.stories.js
  components/00-tokens/effects/shadows.twig
  components/02-molecules/search-result/_yds-search-result.scss
  components/03-organisms/_list-mixins.scss
  components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
  package-lock.json
Labels: pass code review, pass functional review, ready to merge

#192 YALB-945: CSS issue on News & Event page
  components/03-organisms/card-collection/_yds-card-collection.scss
Labels: needs help, needs review, pass code review, pass functional review

#194 YALB-461 - Link: Focus indicator in Firefox
  components/01-atoms/controls/button/_yds-button.scss
Labels: needs review, pass a11y review

#188 YALB-887 - Feedback: Animated underline still not there
  components/01-atoms/controls/control.stories.js
  components/01-atoms/controls/text-link/_yds-text-link.scss
  components/01-atoms/controls/text-link/yds-text-link.twig
  components/02-molecules/accordion/_yds-accordion.scss
  components/02-molecules/alert/_yds-alert.scss
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
  components/02-molecules/callout/_yds-callout.scss
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/search-result/_yds-search-result.scss
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/02-molecules/text/_yds-text-field.scss
  components/03-organisms/site-footer/_yds-site-footer.scss
  components/03-organisms/site-header/_yds-site-header.scss
Labels: pass code review, pass functional review, ready to merge, pass design review

#186 YALB-920 - Forms: Theming next steps
  components/01-atoms/forms/_form-label.twig
  components/01-atoms/forms/_yds-form.scss
  components/03-organisms/component-wrapper/_yds-component-wrapper.scss
  components/03-organisms/component-wrapper/yds-component-wrapper.twig
  components/03-organisms/organisms.scss
Labels: pass code review, pass functional review, ready to merge
