Repository yalesites-org/component-library-twig, pull requests merged in 2023-06, with the labels that each got.

#242 YALB-1196: past events treatment
  components/01-atoms/typography/headings/yds-heading.twig
  components/02-molecules/meta/event-meta/_yds-event-meta.scss
  components/02-molecules/meta/event-meta/yds-event-meta.twig
  components/02-molecules/meta/meta.stories.js
  components/02-molecules/page-title/_yds-page-title.scss
  components/02-molecules/page-title/page-title.stories.js
  components/02-molecules/page-title/yds-page-title.twig
  components/04-page-layouts/cl-page-args.js
  components/05-page-examples/events/event-page.twig
  components/05-page-examples/events/events.stories.js
Labels: pass code review, pass functional review, ready to merge, pass design review

#251 YALB 1282: Bug: Heading color in tab content
  components/01-atoms/images/image/_yds-image.scss
  components/02-molecules/tabs/_yds-tabs.scss
Labels: needs review

#249 YALB-1300: Bug: Error when creating a new event
  components/02-molecules/meta/event-meta/yds-event-meta.twig
Labels: needs review

#253 YALB-1277: Fixes animation to link styles
  components/01-atoms/images/image/_yds-image.scss
Labels: pass code review, pass functional review

#254 YALB-1280: Bug: Media gallery link hover style
  components/03-organisms/galleries/media-grid/_yds-media-grid-modal.scss
Labels: pass code review, pass functional review, ready to merge

#255 YALB-1263 - Layout Builder spacing between components
  components/00-tokens/layout/_layout.scss
  components/02-molecules/banner/action/_yds-action-banner.scss
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/callout/_yds-callout.scss
  components/02-molecules/quick-links/_yds-quick-links.scss
  components/02-molecules/wrapped-image/_yds-wrapped-image.scss
  components/02-molecules/wrapped-image/wrapped-image.stories.js
  components/02-molecules/wrapped-image/yds-wrapped-image.twig
  components/03-organisms/site-header/_yds-site-header.scss
Labels: needs review

#256 YALB-1364 - Bug: Alert banner height (FE)
  components/02-molecules/alert/_yds-alert.scss
  components/02-molecules/alert/alert.stories.js
Labels: pass code review, pass functional review

#258 YALB-1325: Bug: Accessibility issues with Search
  components/03-organisms/menu/utility-nav/yds-utility-nav.twig
  components/03-organisms/site-header/_site-header--secondary.twig
  components/03-organisms/site-header/yds-site-header.twig
Labels: pass code review

#257 YALB-1322 - Bug: Gallery Block - closing x gets cut off (FE)
  components/03-organisms/galleries/media-grid/_yds-media-grid-modal.scss
Labels: pass code review, pass functional review, ready to merge
