Repository yalesites-org/component-library-twig, pull requests merged in 2023-08, with the labels that each got.

#278 YALB-1498: Components: Card animation | YALB-1500: Components Dividers animation | YALB-1502: Components: Quote animation
  components/00-tokens/effects/_effects.scss
  components/00-tokens/effects/yds-animate.js
  components/01-atoms/divider/_yds-divider.scss
  components/01-atoms/divider/divider.stories.js
  components/01-atoms/divider/yds-divider.twig
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/pull-quote/_yds-pull-quote.scss
  components/02-molecules/pull-quote/yds-pull-quote.twig
  components/04-page-layouts/_yds-base.twig
  components/05-page-examples/events/event-page.twig
  components/05-page-examples/events/events.stories.js
  components/05-page-examples/miscellaneous/miscellaneous-page.stories.js
  components/05-page-examples/post/post-article.twig
  components/05-page-examples/post/post.stories.js
  components/05-page-examples/profiles/profile.twig
  components/05-page-examples/profiles/profiles.stories.js
  components/05-page-examples/standard-pages/standard-page-with-banner-left-align.twig
  components/05-page-examples/standard-pages/standard-page-with-banner.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
  components/05-page-examples/standard-pages/standard-page.twig
  components/_settings/config.stories.js
Labels: needs review, pass a11y review

#280 YALB-1478: Views: display modes and dynamic lists
  components/02-molecules/cards/directory-listing-card/directory-listing-card.stories.js
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/examples/_card--examples.twig
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/03-organisms/card-collection/_yds-card-collection.scss
  components/03-organisms/card-collection/card-collection.stories.js
  components/03-organisms/card-collection/yds-card-collection.twig
  components/05-page-examples/_intro-content-examples.twig
  components/05-page-examples/events/_event-collection--example.twig
  components/05-page-examples/post/post-article.twig
  components/05-page-examples/standard-pages/standard-page-with-banner-left-align.twig
  components/05-page-examples/standard-pages/standard-page-with-banner.twig
Labels: needs review

#281 YALB-1483: Footer: Add LinkedIn setting and link
  components/02-molecules/social-links/social-links.yml
Labels: pass code review, pass functional review, ready to merge
