Repository yalesites-org/component-library-twig, pull requests merged in 2024-03, with the labels that each got.

#339 YSP-323: breadcrumb overlayed into text block with heading when page title hidden
  components/02-molecules/page-title/_yds-page-title.scss
  components/05-page-examples/standard-pages/standard-page.stories.js
  components/05-page-examples/standard-pages/standard-page.twig
Labels: pass code review, pass functional review, pass a11y review

#340 YSP-352: Mobile menu hide animation on resize
  components/02-molecules/menu/menu-toggle/yds-menu-toggle.js
  components/03-organisms/site-header/_yds-site-header.scss
  components/03-organisms/site-header/yds-site-header.twig
Labels: pass code review, pass functional review, pass a11y review

#343 YSP-426: Placement for the external link icon on footer logo
  lib/ys_link/config.js
Labels: needs review, pass code review, pass functional review

#344 YSP-375: TwigTweak errors when removing media used in gallery
  components/01-atoms/images/image/_image.twig
  components/03-organisms/galleries/media-grid/_yds-media-grid.scss
  components/03-organisms/galleries/media-grid/media-grid.yml
Labels: pass code review, pass functional review

#341 YALB-363: Design: Serif text in right column gets cut off | YALB-365: Design: Grand Hero Banner overlay header spacing | YALB-424: Removing primary-nav and grand hero results in missing fontawesome
  components/00-tokens/layout/yds-layout.js
  components/01-atoms/images/fa-icons/_yds-fa-icon.twig
  components/01-atoms/tables/_table.scss
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/text/_yds-text-field.scss
  lib/ys_link/builders/sr_only_creator.js
Labels: pass code review, pass functional review, pass a11y review

#342 YSP-366: Card display mode spacing between heading, content, and image
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
  components/02-molecules/cards/directory-listing-card/_yds-directory-listing-card.scss
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
Labels: needs review, pass code review, pass functional review, pass a11y review
