Repository yalesites-org/component-library-twig, pull requests merged in 2024-06, with the labels that each got.

#363 YSP-490, 501, 502, 503, 514: Add Tiles, Facts and Figures, Quote Callout, and Link Grid Blocks
  components/00-tokens/colors/color-component-theme-pairings.twig
  components/00-tokens/colors/color-global-theme-pairings.twig
  components/02-molecules/content-spotlight-portrait/content-spotlights.js
  components/02-molecules/facts-and-figures/_yds-facts-and-figures.scss
  components/02-molecules/facts-and-figures/facts-and-figures.stories.js
  components/02-molecules/facts-and-figures/facts-and-figures.yml
  components/02-molecules/facts-and-figures/yds-facts-and-figures.twig
  components/02-molecules/infographic/infographic.stories.js
  components/02-molecules/infographic/infographic.yml
  components/02-molecules/infographic/yds-infographic.twig
  components/02-molecules/link-grid/_yds-link-grid.scss
  components/02-molecules/link-grid/link-grid.yml
  components/02-molecules/link-grid/yds-link-grid.twig
  components/02-molecules/molecules.scss
  components/02-molecules/quote-callout/_yds-quote-callout.scss
  components/02-molecules/quote-callout/quote-callout.stories.js
  components/02-molecules/quote-callout/quote-callout.yml
  components/02-molecules/quote-callout/yds-quote-callout.twig
  components/02-molecules/standalone-quote/standalone-quote.stories.js
  components/02-molecules/standalone-quote/standalone-quote.yml
  components/02-molecules/standalone-quote/yds-standalone-quote.twig
  components/02-molecules/tile-item/_yds-tile-item.scss
  components/02-molecules/tile-item/tile-item.stories.js
  components/02-molecules/tile-item/tile-item.yml
  components/02-molecules/tile-item/yds-tile-item.js
  components/02-molecules/tile-item/yds-tile-item.twig
  components/03-organisms/facts-and-figures-group/_yds-facts-and-figures-group.scss
  components/03-organisms/facts-and-figures-group/facts-and-figures-group.stories.js
  components/03-organisms/facts-and-figures-group/facts-and-figures-group.yml
  components/03-organisms/facts-and-figures-group/yds-facts-and-figures-group.twig
  components/03-organisms/infographic-group/infographic-group.yml
  components/03-organisms/infographic-group/yds-infographic-group.twig
  components/03-organisms/organisms.scss
  components/03-organisms/tiles/_yds-tiles.scss
  components/03-organisms/tiles/tiles.stories.js
  components/03-organisms/tiles/tiles.yml
  components/03-organisms/tiles/yds-tiles.twig
  components/05-page-examples/standard-pages/standard-page-with-banner-left-align.twig
  components/05-page-examples/standard-pages/standard-page-with-banner.twig
Labels: needs review, Question

#374 YSP-560: Localist: Update Event lists + default image updates
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/cards/reference-card/yds-reference-card.twig
  components/02-molecules/meta/event-meta/_yds-event-meta.scss
  components/02-molecules/meta/event-meta/event-localist.yml
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
Labels: needs review, pass code review, pass functional review

#370 YSP-431 Wire/Add/Tweak Call-to-Action button utility nav
  components/03-organisms/menu/utility-nav/utility-nav.yml
  components/03-organisms/menu/utility-nav/yds-utility-nav.twig
  components/03-organisms/site-header/_yds-site-header.scss
Labels: pass code review, pass functional review, ready to merge

#376 YSP-487: Add JWPlayer Embed
  components/02-molecules/embed/_yds-embed.scss
  components/02-molecules/embed/yds-embed.twig
Labels: needs review, pass functional review, pass a11y review

#373 YSP-554 - Hamburger icon shows on empty menu
  components/03-organisms/site-header/yds-site-header.twig
Labels: pass code review, pass functional review, ready to merge

#367 YSP-509: Add Code Style to WYSIWYG
  components/01-atoms/typography/text/_yds-text.scss
  components/01-atoms/typography/text/yds-text.js
  components/02-molecules/text/text-field.yml
  components/02-molecules/text/typography.stories.js
  package-lock.json
  package.json
Labels: pass code review, pass functional review, ready to merge

#377 YSP-541: Embed: Add Microsoft Forms
  components/02-molecules/embed/_yds-embed.scss
  components/02-molecules/embed/embed.stories.js
Labels: pass code review, pass functional review, ready to merge

#375 YSP-281: Localist Project
  components/01-atoms/images/icons/_yds-icon.twig
  components/02-molecules/cards/custom-card/custom-card.stories.js
  components/02-molecules/cards/custom-card/yds-custom-card.twig
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/examples/_card--examples.twig
  components/02-molecules/cards/reference-card/examples/event-card.yml
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/cards/reference-card/yds-reference-card.twig
  components/02-molecules/meta/event-meta/_yds-event-meta.scss
  components/02-molecules/meta/event-meta/event-localist.yml
  components/02-molecules/meta/event-meta/event-meta-localist.js
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
  components/02-molecules/meta/meta.stories.js
  components/02-molecules/page-title/_yds-page-title.scss
  components/02-molecules/page-title/yds-page-title.twig
  components/04-page-layouts/cl-page-args.js
Labels: pass code review, pass functional review, ready to merge, pass design review

#381 Release
  components/01-atoms/images/icons/_yds-icon.twig
  components/02-molecules/cards/custom-card/custom-card.stories.js
  components/02-molecules/cards/custom-card/yds-custom-card.twig
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/examples/_card--examples.twig
  components/02-molecules/cards/reference-card/examples/event-card.yml
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/cards/reference-card/yds-reference-card.twig
  components/02-molecules/meta/event-meta/_yds-event-meta.scss
  components/02-molecules/meta/event-meta/event-localist.yml
  components/02-molecules/meta/event-meta/event-meta-localist.js
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
  components/02-molecules/meta/meta.stories.js
  components/02-molecules/page-title/_yds-page-title.scss
  components/02-molecules/page-title/yds-page-title.twig
  components/04-page-layouts/cl-page-args.js
Labels: pass code review, ready to merge

#382 YSP-569: V1.4.0 Spotlight in banner area has extra padding above
  components/02-molecules/content-spotlight-portrait/_yds-content-spotlight-portrait.scss
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/05-page-examples/standard-pages/standard-page-banner-spotlights.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
Labels: needs review

#383 Release
  components/02-molecules/content-spotlight-portrait/_yds-content-spotlight-portrait.scss
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/05-page-examples/standard-pages/standard-page-banner-spotlights.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
Labels: needs review
