Repository yalesites-org/component-library-twig, pull requests merged in 2024-04, with the labels that each got.

#351 YSP-430): Canvas user need to allow two call to actions in banner
  components/02-molecules/banner/action/_yds-action-banner.scss
  components/02-molecules/banner/action/yds-action-banner.twig
  components/02-molecules/banner/banner.stories.js
  components/02-molecules/banner/banner.yml
  components/02-molecules/banner/grand-hero.yml
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
Labels: pass code review, pass functional review, pass a11y review

#348 YSP-427 - Hero Banner breadcrumb issue
  components/02-molecules/page-title/_yds-page-title.scss
  components/02-molecules/page-title/page-title.js
  components/02-molecules/page-title/page-title.stories.js
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  components/05-page-examples/standard-pages/standard-page.stories.js
Labels: needs review, pass code review, pass functional review

#346 YSP-413: Stats component | YSP-428: Tiles Components
  components/02-molecules/infographic/_yds-infographic.scss
  components/02-molecules/infographic/infographic.stories.js
  components/02-molecules/infographic/infographic.yml
  components/02-molecules/infographic/yds-infographic.twig
  components/02-molecules/molecules.scss
  components/02-molecules/stat/stat.stories.js
  components/02-molecules/stat/stat.yml
  components/02-molecules/stat/yds-stat.twig
  components/02-molecules/tile-item/_yds-tile-item.scss
  components/02-molecules/tile-item/tile-item.stories.js
  components/02-molecules/tile-item/tile-item.yml
  components/02-molecules/tile-item/yds-tile-item.js
  components/02-molecules/tile-item/yds-tile-item.twig
  components/03-organisms/infographic-group/_yds-infographic-group.scss
  components/03-organisms/infographic-group/infographic-group.stories.js
  components/03-organisms/infographic-group/infographic-group.yml
  components/03-organisms/infographic-group/yds-infographic-group.twig
  components/03-organisms/organisms.scss
  components/03-organisms/stats/stats.yml
  components/03-organisms/stats/yds-stats.twig
  components/03-organisms/tiles/_yds-tiles.scss
  components/03-organisms/tiles/tiles.stories.js
  components/03-organisms/tiles/tiles.yml
  components/03-organisms/tiles/yds-tiles.twig
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#345 YSP-308 - Reference cards: Create components from Designs
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/examples/_card--examples.twig
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/cards/reference-card/yds-reference-card.twig
  components/03-organisms/card-collection/_yds-card-collection.scss
  components/05-page-examples/standard-pages/standard-page-with-sidebar.twig
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#353 YSP-419: Rebrand Twitter to X
  components/00-tokens/colors/color-basic-themes.twig
  components/02-molecules/embed/embed.stories.js
  components/02-molecules/social-links/social-links.yml
  images/icons/x-twitter.svg
Labels: pass code review, pass functional review, ready to merge, pass a11y review
