Repository yalesites-org/component-library-twig, pull requests merged in 2024-08, with the labels that each got.

#394 YSP-604: Grand Hero Video doesn't load on mobile
  components/01-atoms/videos/video-background/yds-video-background.twig
Labels: pass code review, pass functional review, pass a11y review

#389 YSP-581: Mobile hamburger menu not showing up
  components/03-organisms/site-header/yds-site-header.twig
Labels: needs review, pass functional review, pass a11y review

#385 YSP(535): Remove spotlight banner fixes
  components/02-molecules/content-spotlight-portrait/_yds-content-spotlight-portrait.scss
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/05-page-examples/standard-pages/standard-page-banner-spotlights.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
Labels: needs review, pass functional review

#391 YSP-495: Site-wide branding for University groups
  components/03-organisms/site-header/_site-header--secondary.twig
  components/03-organisms/site-header/site-header.stories.js
Labels: pass functional review, pass a11y review

#392 YSP-602: Localist: hybrid 'event experience' missing
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/04-page-layouts/cl-page-args.js
Labels: pass functional review, pass a11y review

#390 YSP-595: Quote Callout/Facts and Figures Link treatment
  components/02-molecules/facts-and-figures/_yds-facts-and-figures.scss
  components/02-molecules/quote-callout/_yds-quote-callout.scss
  components/03-organisms/facts-and-figures-group/_yds-facts-and-figures-group.scss
  components/03-organisms/facts-and-figures-group/yds-facts-and-figures-group.twig
  lib/ys_link/css/ys-link.css
Labels: needs review, pass functional review, pass a11y review, pass design review

#393 YSP-583: Event date display a range
  components/01-atoms/date-time/yds-date-time.twig
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
Labels: needs review, pass code review, pass design review

#397 YSP-625: Submit button color looks disabled when it is not
  components/01-atoms/forms/_yds-form.scss
Labels: released, pass a11y review, pass design review

#399 Bump Tokens to 1.31.0
  package-lock.json
Labels: pass code review, pass functional review, released

#400 Release
  components/01-atoms/forms/_yds-form.scss
  package-lock.json
Labels: needs review
