Repository yalesites-org/component-library-twig, pull requests merged in 2024-05, with the labels that each got.

#361 YSP-496: Increase Site Name Image width
  components/03-organisms/site-header/_yds-site-header.scss
  components/03-organisms/site-header/yds-site-header.twig
Labels: pass code review, pass functional review, pass a11y review

#365 fix(YSP-527): V1.3.0: Reference Card link color contrast
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
Labels: pass functional review, ready to merge, pass a11y review

#369 YSP-519: Tech debt - remove subtle quicklinks from component library
  components/02-molecules/quick-links/_yds-quick-links.scss
  components/02-molecules/quick-links/quick-links.stories.js
  components/02-molecules/quick-links/yds-quick-links.twig
Labels: needs review

#355 YSP-461: Localist: Style Event Meta Block with new designs
  components/01-atoms/images/icons/_yds-icon.twig
  components/02-molecules/cards/custom-card/custom-card.stories.js
  components/02-molecules/cards/custom-card/yds-custom-card.twig
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/examples/_card--examples.twig
  components/02-molecules/cards/reference-card/examples/event-card.yml
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/cards/reference-card/yds-reference-card.twig
  components/02-molecules/meta/event-meta/_yds-event-meta.scss
  components/02-molecules/meta/event-meta/event-localist.yml
  components/02-molecules/meta/event-meta/event-meta-localist.js
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
  components/02-molecules/meta/meta.stories.js
  components/02-molecules/page-title/_yds-page-title.scss
  components/02-molecules/page-title/yds-page-title.twig
  components/04-page-layouts/cl-page-args.js
Labels: pass functional review

#362 Ysp 321 profile vertical images
  components/02-molecules/meta/meta.stories.js
  components/02-molecules/meta/profile-meta/_yds-profile-meta.scss
  components/02-molecules/meta/profile-meta/yds-profile-meta.twig
  components/05-page-examples/profiles/profile.twig
  components/05-page-examples/profiles/profiles.stories.js
Labels: pass code review, pass functional review, ready to merge
