Repository yalesites-org/component-library-twig, pull requests merged in 2024-09, with the labels that each got.

#408 YSP-649: EDT vs EST from Localist causing incorrect time render
  components/02-molecules/meta/event-meta/event-localist.yml
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
Labels: needs review, pass code review, pass functional review

#413 Hotfix Release
  components/02-molecules/meta/event-meta/event-localist.yml
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
Labels: pass code review, pass functional review, ready to merge

#409 JAKALA: Color Palette for ONHA
  .storybook/preview.js
  components/01-atoms/controls/control.stories.js
  components/02-molecules/banner/action/_yds-action-banner.scss
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/callout/_yds-callout.scss
  components/02-molecules/content-spotlight-portrait/_yds-content-spotlight-portrait.scss
  components/02-molecules/facts-and-figures/_yds-facts-and-figures.scss
  components/02-molecules/facts-and-figures/facts-and-figures.stories.js
  components/02-molecules/inline-message/_yds-inline-message.scss
  components/02-molecules/link-grid/_yds-link-grid.scss
  components/02-molecules/meta/profile-meta/_yds-profile-meta.scss
  components/02-molecules/pull-quote/_yds-pull-quote.scss
  components/02-molecules/quote-callout/_yds-quote-callout.scss
  components/02-molecules/quote-callout/quote-callout.stories.js
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/02-molecules/tile-item/_yds-tile-item.scss
  components/03-organisms/facts-and-figures-group/_yds-facts-and-figures-group.scss
  components/03-organisms/facts-and-figures-group/facts-and-figures-group.stories.js
  components/03-organisms/site-header/_site-header--secondary.twig
  components/03-organisms/tiles/tiles.stories.js
  components/05-page-examples/events/events.stories.js
  components/05-page-examples/miscellaneous/miscellaneous-page.stories.js
  components/05-page-examples/post/post-grid.twig
  components/05-page-examples/post/post.stories.js
  components/05-page-examples/profiles/profiles.stories.js
  components/05-page-examples/standard-pages/standard-page.stories.js
  components/_settings/config.stories.js
Labels: pass code review, pass functional review

#411 JAKALA: Add secondary link to Spotlight blocks
  components/02-molecules/content-spotlight-portrait/_yds-content-spotlight-portrait.scss
  components/02-molecules/content-spotlight-portrait/content-spotlight-portrait.stories.js
  components/02-molecules/content-spotlight-portrait/content-spotlight-portrait.yml
  components/02-molecules/content-spotlight-portrait/yds-content-spotlight-portrait.twig
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/02-molecules/text-with-image/text-with-image.stories.js
  components/02-molecules/text-with-image/text-with-image.yml
  components/02-molecules/text-with-image/yds-text-with-image.twig
Labels: pass code review, pass functional review

#418 JAKALA-Clone: Search page content filter
  components/02-molecules/search-result/_yds-search-result.scss
  components/02-molecules/search-result/search-result.yml
  components/02-molecules/search-result/yds-search-result.stories.js
  components/02-molecules/search-result/yds-search-result.twig
Labels: needs review

#416 YSP-640: PRESIDENT: White space under card image
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
Labels: needs review, pass code review, pass functional review, pass a11y review

#412 YSP-641: Image Banner Block
  components/02-molecules/banner/banner.stories.js
  components/02-molecules/banner/image/_yds-image-banner.scss
  components/02-molecules/banner/image/yds-image-banner.twig
Labels: pass functional review, pass a11y review, pass design review

#414 YSP-662: PRESIDENT: allow center or larger view of video block
  components/02-molecules/video/_yds-video.scss
  components/02-molecules/video/video.stories.js
  components/02-molecules/video/video.yml
  components/02-molecules/video/yds-video.twig
Labels: pass functional review, pass design review

#419 YSP-670: Spotlights provide H2 in Banner Section
  components/02-molecules/content-spotlight-portrait/yds-content-spotlight-portrait.twig
  components/02-molecules/text-with-image/yds-text-with-image.twig
Labels: pass functional review, pass a11y review

#405 YSP-646: PRESIDENT: Event time display updates
  components/01-atoms/date-time/yds-date-time.twig
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
  components/02-molecules/meta/event-meta/yds-event-meta.twig
Labels: pass code review, pass functional review, pass a11y review

#415 YSP-666: Breadcrumbs not clickable in Firefox when no banner blocks provided in mega menu mode
  components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
Labels: pass functional review, pass a11y review

#410 JAKALA: Views block enhancements
  .eslintrc.js
  .storybook/jquery-global.js
  .storybook/preview.js
  components/01-atoms/controls/cta/_yds-cta.scss
  components/01-atoms/forms/_yds-form.scss
  components/01-atoms/forms/contact-form-example.twig
  components/01-atoms/forms/select/_yds-select.scss
  components/01-atoms/forms/select/yds-select.js
  components/01-atoms/forms/textfields/_yds-textfields.scss
  components/01-atoms/lists/_yds-list.scss
  components/01-atoms/lists/list.stories.js
  components/01-atoms/lists/taxonomy/categories-list.yml
  components/01-atoms/lists/taxonomy/tags-list.yml
  components/01-atoms/lists/taxonomy/yds-categories-list.twig
  components/01-atoms/lists/taxonomy/yds-tags-list.twig
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/examples/post-card.yml
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/cards/reference-card/yds-reference-card.twig
  components/02-molecules/search-result/_yds-search-result.scss
  package-lock.json
  package.json
Labels: pass code review, pass functional review, pass a11y review, pass design review

#420 JAKALA: Contrast fixes for ONHA color palette
  components/02-molecules/banner/action/_yds-action-banner.scss
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/callout/callout.yml
  components/02-molecules/content-spotlight-portrait/_yds-content-spotlight-portrait.scss
  components/02-molecules/inline-message/_yds-inline-message.scss
  components/02-molecules/inline-message/inline-message.stories.js
  components/02-molecules/quote-callout/_yds-quote-callout.scss
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/02-molecules/tile-item/_yds-tile-item.scss
  components/02-molecules/tile-item/tile-item.stories.js
Labels: pass code review, pass functional review, pass a11y review
