Repository yalesites-org/component-library-twig, pull requests merged in 2025-01, with the labels that each got.

#443 IYY-296 - Fix Views spacing
  components/03-organisms/card-collection/_yds-card-collection.scss
  components/03-organisms/component-wrapper/_yds-component-wrapper.scss
  components/03-organisms/custom-card-collection/_yds-custom-card-collection.scss
Labels: needs review, pass code review, pass functional review

#453 Update Git PR Template Figma URL and remove Percy reference
  .github/pull_request_template.md
Labels: needs review

#452 IYY-302: Add vertical text alignment to Spotlights
  components/02-molecules/content-spotlight-portrait/_yds-content-spotlight-portrait.scss
  components/02-molecules/content-spotlight-portrait/content-spotlight-portrait.stories.js
  components/02-molecules/content-spotlight-portrait/yds-content-spotlight-portrait.twig
  components/02-molecules/molecules.scss
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/02-molecules/text-with-image/text-with-image.stories.js
  components/02-molecules/text-with-image/yds-text-with-image.twig
  components/02-molecules/wrapped-callout/_yds-wrapped-callout.scss
  components/02-molecules/wrapped-callout/wrapped-callout.stories.js
  components/02-molecules/wrapped-callout/wrapped-callout.yml
  components/02-molecules/wrapped-callout/yds-wrapped-callout.twig
Labels: needs review, pass code review, pass functional review

#447 YSP-762: Post Date Refactor
  components/01-atoms/date-time/yds-date-time.twig
  components/05-page-examples/post/post.stories.js
Labels: needs review

#441 IYY:297: Create new "Coral" Theme
  .storybook/preview.js
  package-lock.json
  package.json
Labels: needs review, pass code review, pass functional review

#442 IYY-283: Site editors can create a ½ - ½ layout | IYY-284: Site editors can create a ⅓ - ⅓ - ⅓ layout
  components/00-tokens/layout/_layout.scss
  components/01-atoms/images/image/_yds-image.scss
  components/02-molecules/accordion/_yds-accordion.scss
  components/02-molecules/content-spotlight-portrait/content-spotlights.js
  components/02-molecules/link-grid/_yds-link-grid.scss
  components/03-organisms/layout/layout.stories.js
  components/03-organisms/layout/layout/_layout--example.twig
  components/03-organisms/layout/layout/_yds-layout.scss
  components/03-organisms/layout/layout/yds-layout.twig
  components/03-organisms/organisms.scss
  components/04-page-layouts/page-layouts.scss
Labels: needs review, pass code review

#451 IYY-289: Utility Navigation Dropdown Menu Link Button
  components/01-atoms/controls/base/yds-control.twig
  components/01-atoms/controls/control.stories.js
  components/01-atoms/controls/cta/_yds-cta.scss
  components/01-atoms/controls/cta/yds-cta.twig
  components/02-molecules/menu/_yds-menu-item.twig
  components/03-organisms/menu/utility-nav/_utility-nav--dropdown-menu.twig
  components/03-organisms/menu/utility-nav/_yds-utility-nav.scss
  components/03-organisms/menu/utility-nav/utility-nav-dropdown-menu.js
  components/03-organisms/menu/utility-nav/utility-nav.stories.js
  components/03-organisms/menu/utility-nav/utility-nav.yml
  components/03-organisms/menu/utility-nav/yds-utility-nav.twig
  components/03-organisms/site-header/_yds-site-header.scss
Labels: needs review, pass code review, pass functional review

#454 IYY-294: Accordion Style Variation
  components/02-molecules/accordion/_yds-accordion.scss
  components/02-molecules/accordion/accordion.stories.js
  components/02-molecules/accordion/yds-accordion.twig
Labels: needs review, pass code review

#446 IYY-288: Theme Secondary navigation
  components/02-molecules/accordion/_yds-accordion.scss
  components/02-molecules/menu/menu-in-this-section-toggle/_yds-menu-in-this-section-toggle.scss
  components/02-molecules/menu/menu-in-this-section-toggle/yds-menu-in-this-section-toggle.js
  components/02-molecules/menu/menu-in-this-section-toggle/yds-menu-in-this-section-toggle.twig
  components/02-molecules/molecules.scss
  components/03-organisms/menu/secondary-nav/_yds-secondary-nav.scss
  components/03-organisms/menu/secondary-nav/secondary-nav.stories.js
  components/03-organisms/menu/secondary-nav/secondary-nav.yml
  components/03-organisms/menu/secondary-nav/yds-secondary-nav.js
  components/03-organisms/menu/secondary-nav/yds-secondary-nav.twig
  components/03-organisms/organisms.scss
  components/03-organisms/site-in-this-section/_site-in-this-section.scss
  components/03-organisms/site-in-this-section/site-in-this-section.stories.js
  components/03-organisms/site-in-this-section/yds-site-in-this-section.js
  components/03-organisms/site-in-this-section/yds-site-in-this-section.twig
  components/05-page-examples/standard-pages/standard-page-short.twig
  components/05-page-examples/standard-pages/standard-page.stories.js
  images/icons/circle-chevron-solid.svg
Labels: needs review, pass code review, pass functional review
