Repository yalesites-org/component-library-twig, pull requests merged in 2025-05, with the labels that each got.

#505 IYY-385 :: Table stylign in two columns with a background color
  components/01-atoms/tables/_table.scss
  components/01-atoms/tables/example-tables.twig
  components/01-atoms/tables/table.js
  components/01-atoms/tables/table.stories.js
Labels: needs review, pass functional review, pass design review

#513 Release
  components/01-atoms/tables/_table.scss
  components/01-atoms/tables/example-tables.twig
  components/01-atoms/tables/table.js
  components/01-atoms/tables/table.stories.js
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
  components/03-organisms/layout/layout.stories.js
  components/03-organisms/layout/layout/_yds-layout.scss
  components/03-organisms/layout/layout/yds-layout.twig
  components/03-organisms/layout/two-column/_yds-two-column.scss
  components/03-organisms/menu/secondary-nav/_yds-secondary-nav.scss
  components/03-organisms/site-in-this-section/_site-in-this-section.scss
  components/03-organisms/site-in-this-section/yds-site-in-this-section.js
  components/03-organisms/site-in-this-section/yds-site-in-this-section.twig
Labels: needs review

#514 YSP-912: Change default for social media sharing on Post content type
  components/02-molecules/page-title/yds-page-title.twig
  components/05-page-examples/post/post-article.twig
  components/05-page-examples/post/post.stories.js
Labels: pass code review, pass functional review, ready to merge, pass design review

#515 YSP-928: Layout Builder Block Tables in Dark Mode Unreadable
  components/01-atoms/tables/_table.scss
Labels: pass code review, pass functional review, ready to merge, pass design review

#516 Release
  components/01-atoms/tables/_table.scss
  components/02-molecules/page-title/yds-page-title.twig
  components/05-page-examples/post/post-article.twig
  components/05-page-examples/post/post.stories.js
Labels: needs review

#517 Hotfix: Revert "feat: ysp-738 add conditional to header component for nav dis…
  components/03-organisms/site-header/yds-site-header.twig
Labels: needs review

#518 Hotfix Release
  components/03-organisms/site-header/yds-site-header.twig
Labels: needs review

#524 Hotfix: YSP-951: Breadcrumbs not showing more than 2 trails levels
  components/03-organisms/menu/breadcrumbs/breadcrumbs.stories.js
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig
Labels: pass code review, pass functional review, ready to merge, pass design review

#525 Release
  components/01-atoms/tables/_table.scss
  components/01-atoms/tables/table.js
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/03-organisms/menu/breadcrumbs/breadcrumbs.stories.js
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig
Labels: needs review

#493 YSP-814 :: Remove `Show Thumbnails` in reference card to use `with-image`
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/cards/reference-card/yds-reference-card.twig
Labels: needs review, pass code review, pass functional review, ready to merge
