Repository yalesites-org/component-library-twig, pull requests merged in 2025-04, with the labels that each got.

#488 YSP-738 :: Reimplement hiding hamburger menu if no menu items exist
  components/03-organisms/site-header/yds-site-header.twig
Labels: pass functional review, ready to merge, pass design review

#485 YSP-844: Event Meta Block Date Visibility Improvements
  components/02-molecules/cards/reference-card/yds-reference-card.twig
  components/02-molecules/meta/event-meta/event-localist.yml
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
  components/02-molecules/meta/meta.stories.js
  components/04-page-layouts/cl-page-args.js
Labels: needs review

#494 YSP-370: Add Offset/Inline Design Options to Landscape Spotlight Block
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/02-molecules/text-with-image/text-with-image.stories.js
  components/02-molecules/text-with-image/yds-text-with-image.twig
Labels: pass functional review

#490 YSP-761 :: Add available blocks to regions for new layouts
  components/01-atoms/controls/control.stories.js
  components/01-atoms/controls/cta/_yds-cta-examples.twig
  components/01-atoms/controls/cta/_yds-cta.scss
  components/01-atoms/divider/_yds-divider.scss
  components/01-atoms/divider/divider.stories.js
  components/01-atoms/forms/_yds-form.scss
  components/01-atoms/forms/contact-form-example.twig
  components/01-atoms/forms/forms.stories.js
  components/01-atoms/forms/textfields/_yds-textfields.scss
  components/02-molecules/accordion/_yds-accordion.scss
  components/02-molecules/accordion/accordion.stories.js
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/link-grid/_yds-link-grid.scss
  components/02-molecules/pull-quote/_yds-pull-quote.scss
  components/02-molecules/pull-quote/pull-quote.stories.js
  components/02-molecules/tabs/_yds-tabs.scss
  components/02-molecules/tabs/tabs.stories.js
  components/03-organisms/layout/layout/_yds-layout.scss
Labels: pass code review, pass functional review, ready to merge

#495 Release
  components/01-atoms/controls/control.stories.js
  components/01-atoms/controls/cta/_yds-cta-examples.twig
  components/01-atoms/controls/cta/_yds-cta.scss
  components/01-atoms/divider/_yds-divider.scss
  components/01-atoms/divider/divider.stories.js
  components/01-atoms/forms/_yds-form.scss
  components/01-atoms/forms/contact-form-example.twig
  components/01-atoms/forms/forms.stories.js
  components/01-atoms/forms/textfields/_yds-textfields.scss
  components/02-molecules/accordion/_yds-accordion.scss
  components/02-molecules/accordion/accordion.stories.js
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/yds-reference-card.twig
  components/02-molecules/link-grid/_yds-link-grid.scss
  components/02-molecules/meta/event-meta/event-localist.yml
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
  components/02-molecules/meta/meta.stories.js
  components/02-molecules/pull-quote/_yds-pull-quote.scss
  components/02-molecules/pull-quote/pull-quote.stories.js
  components/02-molecules/tabs/_yds-tabs.scss
  components/02-molecules/tabs/tabs.stories.js
  components/02-molecules/text-with-image/_yds-text-with-image.scss
  components/02-molecules/text-with-image/text-with-image.stories.js
  components/02-molecules/text-with-image/yds-text-with-image.twig
  components/03-organisms/layout/layout/_yds-layout.scss
  components/03-organisms/site-header/yds-site-header.twig
  components/04-page-layouts/cl-page-args.js
Labels: needs review

#492 YSP-716 :: Add "Contained Narrow" Design Option to Grand Hero Block
  components/02-molecules/banner/banner.stories.js
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
Labels: pass functional review, ready to merge, pass design review

#480 YSP-482: Card spacing fix
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
Labels: pass functional review

#499 YSP-589: Add Page Content Type Support to Reference Card Block
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/examples/page-card.yml
  components/02-molecules/cards/reference-card/reference-card.stories.js
Labels: pass code review, pass functional review, ready to merge, pass design review

#502 YSP-874: Quote Block 'Bar Right' Style Alignment Issues in Narrow Sections
  components/02-molecules/pull-quote/_yds-pull-quote.scss
Labels: pass code review, pass functional review, ready to merge, pass design review

#501 YSP-882: Quote styling doesn't adapt to section background colors
  components/02-molecules/pull-quote/_yds-pull-quote.scss
  components/02-molecules/pull-quote/pull-quote.stories.js
Labels: pass code review, pass functional review, ready to merge, pass design review

#491 IYY-345: Breadcrumbs at level 2 instead of level 3
  components/03-organisms/menu/breadcrumbs/breadcrumbs.stories.js
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig
Labels: pass functional review, pass design review

#498 IYY-375 : Dropdown scroll issue
  components/03-organisms/menu/utility-nav/_yds-utility-nav.scss
  components/03-organisms/menu/utility-nav/utility-nav-dropdown-menu.js
  components/03-organisms/menu/utility-nav/utility-nav.stories.js
  components/03-organisms/menu/utility-nav/yds-utility-nav--example.twig
Labels: pass functional review, ready to merge, pass design review

#500 YSP-803: Reduce Excessive Padding Between Breadcrumbs and Banner Blocks
  components/02-molecules/page-title/_yds-page-title.scss
  components/03-organisms/layout/two-column/_yds-two-column.scss
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  components/04-page-layouts/page-layouts.scss
Labels: pass functional review, ready to merge

#504 Release
  components/01-atoms/controls/control.stories.js
  components/01-atoms/controls/cta/_yds-cta.scss
  components/02-molecules/banner/banner.stories.js
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/examples/page-card.yml
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/page-title/_yds-page-title.scss
  components/02-molecules/pull-quote/_yds-pull-quote.scss
  components/02-molecules/pull-quote/pull-quote.stories.js
  components/03-organisms/layout/two-column/_yds-two-column.scss
  components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
  components/03-organisms/menu/breadcrumbs/breadcrumbs.stories.js
  components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig
  components/03-organisms/menu/utility-nav/_yds-utility-nav.scss
  components/03-organisms/menu/utility-nav/utility-nav-dropdown-menu.js
  components/03-organisms/menu/utility-nav/utility-nav.stories.js
  components/03-organisms/menu/utility-nav/yds-utility-nav--example.twig
  components/04-page-layouts/page-layouts.scss
Labels: ready to merge

#506 YSP-875: Text: Tables in a section have a color contrast issue
  components/01-atoms/tables/_table.scss
Labels: pass functional review, ready to merge

#507 YSP-892: Design treatment for active Content Collect parent menu items
  components/03-organisms/menu/secondary-nav/_yds-secondary-nav.scss
Labels: pass code review, pass functional review, ready to merge, pass design review

#510 YSP-892: Design treatment for active Content Collection parent menu items and location move
  components/03-organisms/menu/secondary-nav/_yds-secondary-nav.scss
  components/03-organisms/site-in-this-section/_site-in-this-section.scss
  components/03-organisms/site-in-this-section/yds-site-in-this-section.js
Labels: pass code review, pass functional review, ready to merge, pass design review

#508 YSP-896: Accessibility: Secondary scroll arrows unlabeled
  components/03-organisms/site-in-this-section/yds-site-in-this-section.twig
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#503 YSP-863 :: Add Section Padding Options
  components/03-organisms/layout/layout.stories.js
  components/03-organisms/layout/layout/_yds-layout.scss
  components/03-organisms/layout/layout/yds-layout.twig
  components/03-organisms/layout/two-column/_yds-two-column.scss
Labels: pass code review, pass functional review, ready to merge, pass design review

#511 LIB: ST-Overlay-PNG
  components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
  components/02-molecules/banner/grand-hero/yds-grand-hero.twig
Labels: pass code review, pass functional review, ready to merge
