Repository yalesites-org/component-library-twig, pull requests merged in 2025-09, with the labels that each got.

#556 YSP-1112: Mobile Navigation Menu Appears Behind Content Collection
  components/03-organisms/site-in-this-section/_site-in-this-section.scss
Labels: pass code review, pass functional review, ready to merge, pass design review

#550 YSP-1039: Embed: Google Calendar
  components/02-molecules/embed/_yds-embed.scss
  components/02-molecules/embed/embed.stories.js
Labels: pass code review, pass functional review, ready to merge, pass a11y review, pass design review

#535 YSE-106: ELTI site updates and Resource Content Type additions
  components/01-atoms/date-time/yds-date-time.twig
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/examples/_card--examples.twig
  components/02-molecules/cards/reference-card/examples/resource-card.yml
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/meta/meta.stories.js
  components/02-molecules/meta/resource-meta/_yds-resource-meta--metadata.twig
  components/02-molecules/meta/resource-meta/_yds-resource-meta.scss
  components/02-molecules/meta/resource-meta/resource-meta.yml
  components/02-molecules/meta/resource-meta/yds-resource-meta.twig
  components/02-molecules/molecules.scss
  components/03-organisms/card-collection/card-collection.stories.js
  components/05-page-examples/resources/_resource-collection--example.twig
  components/05-page-examples/resources/resource-grid.twig
  components/05-page-examples/resources/resource-list.twig
  components/05-page-examples/resources/resource-page.twig
  components/05-page-examples/resources/resources.stories.js
Labels: pass code review, pass functional review, ready to merge

#564 YSP-1141: RC: AI Palette missing colors in theme settings
  package-lock.json
Labels: pass functional review, ready to merge, pass design review

#565 YSP-1142: RC: Site menu z-index
  components/03-organisms/site-header/_yds-site-header.scss
Labels: pass code review, pass functional review, ready to merge, pass design review

#567 Release (RC Fix 1)
  components/02-molecules/meta/resource-meta/_yds-resource-meta.scss
  components/02-molecules/meta/resource-meta/yds-resource-meta.twig
  components/03-organisms/site-header/_yds-site-header.scss
  package-lock.json
Labels: ready to merge
