Repository yalesites-org/component-library-twig, pull requests merged in 2025-02, with the labels that each got.

#460 YSP-768: Update category styling on reference cards
  components/01-atoms/lists/_yds-list.scss
  components/02-molecules/cards/reference-card/reference-card.stories.js
Labels: needs review, pass code review, pass functional review

#459 YSP-564: Custom Cards on mobile responsiveness
  components/02-molecules/cards/custom-card/_yds-custom-card.scss
Labels: pass code review, pass functional review

#456 YSP-785: A11y: New Haven Green + ONHA Mega Footer link contrast
  components/02-molecules/link-group/_yds-link-group.scss
  components/03-organisms/site-footer/_site-footer-mega.twig
  components/03-organisms/site-footer/_yds-site-footer.scss
  components/03-organisms/site-footer/site-footer.stories.js
Labels: pass code review, ready to merge, pass a11y review, pass design review

#462 YSP-769: Add "Pin to Top" visual indicator
  components/01-atoms/typography/headings/yds-heading.twig
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/cards/reference-card/yds-reference-card.twig
  components/03-organisms/card-collection/card-collection.stories.js
Labels: needs review, pass functional review

#466 IYY-327: Support Video Embed on Image Banner
  components/00-tokens/layout/_layout.scss
  components/02-molecules/banner/banner.stories.js
  components/02-molecules/banner/video/yds-video-banner.scss
  components/02-molecules/banner/video/yds-video-banner.twig
  components/02-molecules/molecules.scss
Labels: needs review, pass code review, pass functional review

#455 IYY-280: Visitors can share Posts
  components/02-molecules/meta/basic-meta/_yds-basic-meta.scss
  components/02-molecules/page-title/_yds-page-title.scss
  components/02-molecules/page-title/page-title.stories.js
  components/02-molecules/page-title/yds-page-title.twig
  images/icons/envelope-solid.svg
  lib/link-treatment/link-treatment.js
Labels: needs review, pass code review

#463 IYY-290: Show CAS'd content in Menu Links
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
  components/02-molecules/cards/reference-card/examples/post-card.yml
  components/02-molecules/cards/reference-card/reference-card.stories.js
  components/02-molecules/cards/reference-card/yds-reference-card.twig
  components/02-molecules/menu/_yds-menu-item.twig
  components/03-organisms/menu/primary-nav/primary-nav.yml
  lib/link-treatment/link-treatment.js
Labels: needs review, pass code review, pass functional review

#474 Feedback v1.13.0-1: Add empty state and style updates to taxonomy display
  components/02-molecules/taxonomy-display/_yds-taxonomy-display--links.twig
  components/02-molecules/taxonomy-display/_yds-taxonomy-display.scss
  components/02-molecules/taxonomy-display/taxonomy-display.stories.js
  components/02-molecules/taxonomy-display/taxonomy-display.yml
  components/02-molecules/taxonomy-display/yds-taxonomy-display.twig
Labels: needs review

#450 IYY-285: Site editors can add a caption to Image Banner | Update Image Banner component to use caption
  components/02-molecules/banner/banner.stories.js
  components/02-molecules/banner/image/yds-image-banner.scss
  components/02-molecules/banner/image/yds-image-banner.twig
Labels: ready to merge

#475 Release
  components/02-molecules/taxonomy-display/_yds-taxonomy-display--links.twig
  components/02-molecules/taxonomy-display/_yds-taxonomy-display.scss
  components/02-molecules/taxonomy-display/taxonomy-display.stories.js
  components/02-molecules/taxonomy-display/taxonomy-display.yml
  components/02-molecules/taxonomy-display/yds-taxonomy-display.twig
Labels: needs review

#476 v1.13.0 Feedback Changes 2
  components/01-atoms/forms/_yds-form.scss
Labels: work in progress

#477 Release (v1.13.0 feedback fixes 2)
  components/01-atoms/forms/_yds-form.scss
Labels: needs review

#461 IYY-321: Posts can have an tagline (eyebrow)
  components/02-molecules/cards/reference-card/_yds-reference-card.scss
Labels: needs review, pass code review, pass functional review

#473 IYY-281: Visitors can see an estimated read-time on Posts
  .storybook/preview.js
  components/02-molecules/molecules.scss
  components/02-molecules/page-title/yds-page-title.twig
  components/02-molecules/read-time/read-time.stories.js
  components/02-molecules/read-time/yds-read-time.js
  components/02-molecules/read-time/yds-read-time.scss
  components/02-molecules/read-time/yds-read-time.twig
  components/05-page-examples/post/post-article.twig
  components/05-page-examples/post/post.stories.js
Labels: needs review

#481 Hotfix: v1.13.0: Add conditional calendar button
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
  components/02-molecules/meta/meta.stories.js
  components/04-page-layouts/cl-page-args.js
Labels: needs review, pass functional review, ready to merge

#482 Release
  components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
  components/02-molecules/meta/meta.stories.js
  components/04-page-layouts/cl-page-args.js
Labels: needs review
